# Generated by Django 5.0.3 on 2024-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='academic_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='additional_materials',
            field=models.FileField(blank=True, null=True, upload_to='additional_materials/'),
        ),
        migrations.AddField(
            model_name='order',
            name='discipline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_paper',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
