# Generated by Django 5.0.3 on 2024-08-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_order_academic_level_order_additional_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
